enum Page {
  INDEX_PAGE = 'INDEX_PAGE',
  AUDIT_HISTORY_PAGE = 'AUDIT_HISTORY_PAGE',
  AUDIT_DETAIL_PAGE = 'AUDIT_DETAIL_PAGE',
  AUDIT_COMBINED_TRANSACTIONS_PAGE = 'AUDIT_COMBINED_TRANSACTIONS_PAGE',
}

export default Page
