trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'My-Service-Connection'
  subscriptionId: '747381f4-e81f-4a43-bf68-ced6a1e14edf'
  resourceGroup: 'rg-monitoring'

steps:

- checkout: self

- task: AzureCLI@2
  displayName: Deploy Portal Dashboard
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az account set --subscription $(subscriptionId)

      az deployment group create \
        --resource-group $(resourceGroup) \
        --template-file dashboards/dashboard.json \
        --parameters \
          dashboardName="Prisoner Finance - Dashboard" \
          location="$(location)" \
          workspaceId="$(workspaceId)" \
          appInsightsId="$(appInsightsId)"
